version: 0.2

phases:
 pre_build:
  commands:
   - echo Logging in to ECR..
   - aws --version
   - $(aws ecr get-login --no-include-email)
   - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 159195950120.dkr.ecr.us-east-2.amazonaws.com
   - echo Image name - $REPOSITORY_URI:latest
 build:
  commands:
    - echo Build started on date
    - echo Building the Docker image...          
    - docker build --tag $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
 post_build:
  commands:
    - echo pushing the image to ECR
    - echo "docker push $REPOSITORY_URI:latest"
    - docker push $REPOSITORY_URI:latest
    - echo "Docker Image Push to ECR Completed -  $REPOSITORY_URI:$TAG"    

# #artifacts:
#  #files: build.json

version: 0.0
os: ubuntu
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
