version: 0.2

phases:
 pre_build:
  commands:
   - echo Logging in to ECR..
   - $(aws ecr get-login --no-include-email)
   - aws ecr get-login-password --region us-east-1 | docker login --username $USERNAME --password-stdin $PASSWORD
   - echo Image name - $REPOSITORY_URI:$TAG
 build:
  commands:
    - echo Build started on date
    - echo Building the Docker image...          
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build:
  commands:
    - echo pushing the image to ECR
    - echo "docker push $REPOSITORY_URI:$TAG"
    - docker push $REPOSITORY_URI:$TAG
    - echo "Docker Image Push to ECR Completed -  $REPOSITORY_URI:$IMAGE_TAG"    

# #artifacts:
#  #files: build.json
